---
# file: roles/homebrew-cask/vars/main.yml

#
# e.g.
# - package_name
# or
# { name: package_name, state: package_state }
#
# state choices: [present, absent, installed, uninstalled] (default: present)
homebrew_cask_packages:
  # - 1password
  # See this for licence migration (MAS -> AWS):
  # https://support.1password.com/switch-from-mac-app-store/
  # https://discussions.agilebits.com/discussion/38591/installing-chrome-and-1p-via-homebrew-cask
  # https://discussions.agilebits.com/discussion/56638/cant-switch-the-version-of-1password-6-from-mac-app-store-to-the-agilebits-store
  - alfred
  # - amazon-cloud-drive
  # - android-studio
  # - anki
  - appcleaner
  - arduino
  - atom
  - bettertouchtool
  - boostnote
  - brackets
  # - caffeine              # Use Amphetamine instead?
  # - cloud                 # Use Beem instead?
  # - colloquy              # Make sure it is usable i.e. do the settings
  - dash
  # - dayone-cli
  - docker                  # Install:
                            # - `docker-completion`
                            # - `docker-completion`
                            # - `docker-completion`
                            # brew formulae alongside this Docker for Mac cask
                            # formula
                            #
                            # OR
                            #
                            # Install:
                            # - `docker`
                            # - `docker-machine`
                            # - `docker-compose`
                            # brew formulae alongside VirtualBox
                            #
                            # NOTE: The Bash completion brew formulae listed
                            #       the section above do not need to be
                            #       installed as `docker`, `docker-machine` and
                            #       `docker-compose` brew formulae include them
  - dropbox
  # - droplr
  # - dropzone
  # - duet
  - evernote
  # - fantastical           # What to do for licence paid
  # - filezilla
  - firefox
  # - flume
  - flux
  # - geektool
  # - gitbook
  - gitee
  - github
  # - githubpulse
  - gitter
  - gitup
  - google-chrome
  - google-cloud-sdk
  - google-drive
  # - google-hangouts
  - google-japanese-ime
  # - hocus-focus
  # - hunt-x
  - imageoptim
  - ionic-lab
  # - iterm2
  - iterm2-beta           # Tap caskroom/versions
  # - iterm2-nightly        # Tap caskroom/versions
  # - istat-menus           # Licensed
  - jadengeller-helium
  - java                  # Install Java; tap caskroom/versions if multiple versions needed
  # - jewelrybox
  - karabiner-elements
  - keycastr              # brew-cask not working; installed via GitHub repo
  - kindle
  - kitematic             # Docker GUI
  # - kobito                # Removed from the cask list
  # - kod
  - libreoffice
  # - lighttable
  # - limechat              # Make sure it is usable i.e. do the settings
  # - loading
  - macdown
  # - mactex                # TODO: This said to be a dependency for octave
  - mactracker
  # - mailbox
  - mamp
  # - marked                # What to do for licence paid
  - marp
  # - microsoft-office      # Install or not
  # - mindnode-pro          # What to do for licence paid
  - mojibar
  # - moom                  # See licence migration (MAS -> Direct): https://manytricks.com/blog/?page_id=2208
  # - mou
  # - noizio
  - now
  - obs
  # - openemu
  # - packer
  - pixate-studio
  - polymail
  - prefs-editor          # A free third party plist editor looks compelling
  # - processing
  # - recordit
  # - revisions
  # - robomongo             # Some describe this is the MongoDB equivalent of Sequel Pro
  - rocket
  # - send-to-kindle
  - sequel-pro            # GUI tool for MySQL
  # - shuttle
  # - sixtyforce            # Licence key
  - skitch
  - skype
  - slack
  - soundflower
  - sourcetree
  # - spectacle
  # - spotify
  - sublime-text          # Now version 3 can be installed
  # - sublime-text-dev      # 3 is now a standard cask; tap caskroom/versions to install
  - the-unarchiver
  - there
  - vagrant
  # - vagrant-manager
  - vanilla
  # - vectr
  - virtualbox
  - vivaldi
  - vlc
  # - vuze
  # - wi2-connect         # Removed from the cask list
  # - wineskin-winery
  # - xampp
  # - xmarks-safari
  - xquartz

  ##############################################################################
  # QuickLook plugins
  # https://github.com/sindresorhus/quick-look-plugins
  ##############################################################################

  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - quicklook-json
  - qlimagesize
  - webpquicklook
  - suspicious-package
  - quicklookase
  - qlvideo
  - provisionql
  - quicklookapk
  - quicklook-pat

  ##############################################################################
  # homebrew-fonts
  ##############################################################################

  - font-droidsansmono-nerd-font
  - font-fantasque-sans-mono
  - font-fantasquesansmono-nerd-font
  - font-fira-code
