---
# file: roles/homebrew/vars/main.yml

# Tap external homebrew repositories.
#
# e.g.
# - homebrew/binary
homebrew_taps:
  - caskroom/cask
  # - caskroom/drivers
  # - caskroom/eid
  - caskroom/fonts
  - caskroom/versions
  # - heroku/brew
  - homebrew/core
  - homebrew/livecheck
  - homebrew/services
  - jesseduffield/lazygit
  - moncho/dry
  # - { tap: mkchoi212/fac, url: 'https://github.com/mkchoi212/fac.git' }
  - vitorgalvao/tiny-scripts

  # - heroku/brew
  # - homebrew/cask
  # - homebrew/cask-drivers
  # - homebrew/cask-eid
  # - homebrew/cask-fonts
  # - homebrew/cask-versions
  # - homebrew/core
  # - homebrew/livecheck
  # - homebrew/services
  # - mkchoi212/fac
  # - moncho/dry
  # - vitorgalvao/tiny-scripts
# Manage homebrew packages.
#
# e.g.
# - package_name
# or
# { name: package_name, state: package_state, install_options: [with-baz, enable-debag] }
#
# state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
# install_options: string or sequence (default: none)
homebrew_packages:
  # All the packages commented out below are potentially to be installed later
  # on. They are collected through surfing the web and seem compelling to me;
  # thus, I listed them up in this playbook file. I commented them out because
  # I do not know what they are and/or how they behave exactly.
  - { name: asciinema }
  - { name: ack }
  # - { name: android-sdk }     # Cordova requires API 22 (as of Nov 2015)
  - { name: ansible }
  - { name: archey }
  # - { name: autojump }        # Like a predecessor of z and fasd
  # - { name: awscli }          # brew info to check what the caveats are
  - { name: bash }            # Install Bash 4;
                              # NOTE:
                              # Do the following things:
                              # 1. Add `/usr/local/bin/bash` to `/etc/shells`
                              # 2. Do `chsh -s /usr/local/bin/bash`
  - { name: bat }
  # - { name: boot2docker }
  # - { name: brew-cask }       # Tap caskroom/cask to install:
                              # NOTE:
                              # As of the release of v0.60.0, it is no longer
                              # necessary to `brew install brew-cask`.
                              # `brew tap caskroom/cask` will install
                              # `brew-cask` as a Homebrew external command, and
                              # `brew update` will keep it up-to-date.
  - { name: cabextract }
  - { name: cask-repair }     # Tap vitorgalvao/tiny-scripts to install
  - { name: ccat }
  - { name: cmake }
  - { name: colordiff }
  - { name: composer }
  - { name: cowsay }
  - { name: ctags }           # I don't know what this is exactly
  - { name: ctop }
  # - { name: curl }            # TODO: Better if you install this over the default one?
  # - { name: dark-mode }
  # - { name: dep }             # Compare with `glide`
  - { name: diff-so-fancy }
  # - { name: dnsmasq }
  # - { name: docker }          # Commented out in favour of Docker for Mac installation
  # - { name: docker-compose }  # Commented out in favour of Docker for Mac installation
  # - { name: docker-machine }  # Commented out in favour of Docker for Mac installation
  - { name: dry }             # Tap `moncho/dry` to install
  - { name: emacs, install_options: with-cocoa }
  - { name: fac }             # Tap `mkchoi212/fac https://github.com/mkchoi212/fac.git` to install
  # - { name: fasd }            # Like a successor of autojump and z
  - { name: ffmpeg }
  - { name: fish }
  - { name: figlet }          # Similar to toilet
  - { name: fortune }
  - { name: fzf }
  - { name: gcc }
  # - { name: gettext }
  # - { name: gifsicle }
  - { name: gist }
  - { name: git }
  - { name: git-cal }
  - { name: git-flow }
    # - { name: git-lfs }         # TODO: How is this helpful?
  - { name: git-sizer }
  - { name: glances }
    # - { name: glide }           # Compare with `dep`
  - { name: go }
  - { name: grv }
  - { name: heroku-toolbelt }
  - { name: htop }
  - { name: httpd }
  - { name: httpie }
  - { name: hub }
  - { name: imagemagick }
  - { name: jdupes }
  - { name: jq }
  - { name: lazygit }
  - { name: less }
  - { name: lua }
  # - { name: macvim, install_options: with-override-system-vim }
  - { name: magic-wormhole }
  - { name: mariadb }       # Drop-in replacement for MySQL
  - { name: markdown }
  - { name: mas }             # Mac App Store command line interface
  # - { name: memcached }
  - { name: mercurial }
  - { name: mongodb }
  - { name: mutt }
  - { name: mycli }
  # - { name: mysql }
  - { name: nano }
  - { name: neofetch }
  - { name: newsboat }
  - { name: nginx }
  # - { name: node }            # Use nvm to install
  # - { name: nvm }             # Not officially supported; see how to install at https://github.com/creationix/nvm
  # - { name: octave }
  # - { name: openssl }         # Specify some options if needed
  # - { name: packer }
  - { name: peco }
  # - { name: php@5.6 }
  # - { name: php@7.0 }
  # - { name: php@7.1 }
  - { name: pipenv }
  - { name: pstree }
  - { name: pv }
  - { name: pyenv }
  - { name: pyenv-virtualenv }
  - { name: python }            # Python 3
  - { name: python@2 }          # Python 2
  - { name: rbenv }
  - { name: rbenv-default-gems }
  # - { name: rbenv-gem-rehash } # DEPRECATED
  - { name: readline }
  - { name: reattach-to-user-namespace }
  # - { name: redis }
  - { name: rmlint }
  # - { name: rsync }
  - { name: ruby-build }
  # - { name: s3cmd }
  - { name: screenfetch }
  - { name: source-highlight }
  - { name: speedtest_cli }   # NOTE: pip installation is seemingly default
  - { name: sqlite }
  - { name: stern }
    # - { name: stormssh }      # TODO: See how this can be helpful
  - { name: terraform }
  # - { name: the_platinum_searcher }
  - { name: the_silver_searcher }
  - { name: tidy-html5 }
  # - { name: tig }
  - { name: tmux }
  - { name: toilet }          # Similar to figlet
  - { name: tor }
  - { name: tree }
  - { name: unrar }
  - { name: unzip }
  - { name: vim, install_options: with-override-system-vi }
  - { name: watch }
  - { name: wget }            # TODO: Understand why some people install this
  - { name: wifi-password }
  - { name: wp-cli }
  - { name: yarn, install_options: without-node } # Requires nvm or equivalent
  - { name: youtube-dl }
  - { name: z }               # Like a successor of autojump, predecessor of fasd
  - { name: zsh }
  - { name: zsh-completions }

  ##############################################################################
  # Bash completions
  ##############################################################################

  - { name: apm-bash-completion }
  - { name: bash-completion@2 }
  # - { name: brew-cask-completion } # No longer needed
  - { name: bundler-completion }
  - { name: docker-completion }
  - { name: docker-machine-completion }
  - { name: docker-compose-completion }
  - { name: gem-completion }
  - { name: grunt-completion }
  - { name: launchctl-completion }
  - { name: open-completion }
  - { name: pip-completion }
  - { name: rails-completion }
  - { name: rake-completion }
  - { name: ruby-completion }
  - { name: tmuxinator-completion }
  - { name: vagrant-completion }
  - { name: wpcli-completion }

  ##############################################################################
  # GNU command line tools
  ##############################################################################

  # - { name: gnupg }           # gpg
  # - { name: gnupg2 }          # gpg2
  # - { name: gnuplot,
  #     install_options: with-x11 } # Version 5; it has some bug when outputting graph
  # - { name: gnuplot@4,
  #     install_options: with-x11 } # NOTE:
                                    # This was needed if saving an Octave plot
                                    # as a user-specified external image file.
                                    # The latest version 5.0.2 (Jan 2016)
                                    # has some bugs and does not output
                                    # the plot properly.
  # - { name: gnu-indent }      # --with-default-names
  # - { name: gnu-sed }         # --with-default-names
  # - { name: gnu-tar }         # --with-default-names
  # - { name: gnu-which }       # --with-default-names
  # - { name: grep }            # --with-default-names

  ##############################################################################
  # Utility tools
  ##############################################################################

  - { name: coreutils }
  # - { name: moreutils }
  # - { name: binutils }
  # - { name: diffutils }
  # - { name: findutils }
